apiVersion: v1
kind: Secret
metadata:
  name: payments-worker-secret
  namespace: estore
stringData:
  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-worker
  namespace: estore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-worker
  template:
    metadata:
      labels:
        app: payments-worker
    spec:
      initContainers:
        - name: wait-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo "waiting for rabbitmq..."; sleep 2; done']
      containers:
        - name: payments-worker
          image: payments-worker:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: payments-worker-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
