apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
  namespace: estore
stringData:
  RABBITMQ_URL: amqp://guest:guest@rabbitmq.estore.svc.cluster.local:5672
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-auth
  namespace: estore
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: RABBITMQ_URL
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payments-worker-scaler
  namespace: estore
spec:
  scaleTargetRef:
    name: payments-worker
  minReplicaCount: 0
  maxReplicaCount: 5
  pollingInterval: 5
  cooldownPeriod: 30
  triggers:
    - type: rabbitmq
      metadata:
        queueName: payments
        mode: QueueLength
        value: "100"
        protocol: auto
      authenticationRef:
        name: rabbitmq-auth
