apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-rbac.yaml
  - prometheus.yaml
configMapGenerator:
  - name: prometheus-config
    namespace: estore
    files:
      - prometheus.yml=prometheus-config.yaml
    options:
      disableNameSuffixHash: true
